[project]
name = "linefollowerdevkit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=3.4.3",
    "bleak>=0.22.3",
    "ruff>=0.7.0",
]
